" Neobundle settings
" --
set runtimepath+=~/.vim/bundle/neobundle.vim/
filetype plugin indent off

call neobundle#begin(expand('~/.vim/bundle/'))
  NeoBundleFetch 'Shougo/neobundle.vim'
  runtime! bundle.d/*.vim
call neobundle#end()

filetype plugin indent on
NeoBundleCheck

" include config
" --
set runtimepath+=~/.vim/
runtime! config.d/*.vim
