" --
" basic settings.
syntax on
colorscheme desert
set showmatch
set matchtime=1

" shortcut
nnoremap <silent><C-e> :NERDTreeToggle<CR>

" --
" Neobundle settings.
set runtimepath+=~/.vim/bundle/neobundle.vim/
filetype plugin indent off

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimproc', {
        \ 'build' : {
        \     'windows' : 'make -f make_mingw32.mak',
        \     'cygwin' : 'make -f make_cygwin.mak',
        \     'mac' : 'make -f make_mac.mak',
        \     'unix' : 'make -f make_unix.mak',
        \    },
        \ }
NeoBundle 'vim-scripts/twilight'
NeoBundle 'scrooloose/nerdtree'
call neobundle#end()

filetype plugin indent on
NeoBundleCheck
