" basic settings
" --
syntax on
colorscheme desert
set showmatch
set matchtime=1

" Neobundle settings
" --
set runtimepath+=~/.vim/bundle/neobundle.vim/
filetype plugin indent off

call neobundle#begin(expand('~/.vim/bundle/'))
  NeoBundleFetch 'Shougo/neobundle.vim'
  source ~/.vim/bundles.vim
call neobundle#end()

filetype plugin indent on
NeoBundleCheck

" config
source ~/.vim/config.vim
